# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Hello, I'm"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "Blog"
    href:           "//leyth.xyz/blog"
  - name:           "Projects"
    href:           "//leyth.xyz/projects"
  - name:           "Resume"
    href:           "//leyth.xyz/resume"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
